#include "networking/routes.h"

Routes::Routes(CommonSuperClass *parent) : CommonSuperClass(parent), enums(new Enums) {}

QUrl Routes::get_host_url() const { return host; }

QUrl Routes::post_api_shop_create() const { return *enums->_urls.POST_API_SHOP_SHOPS_CREATE; }
QUrl Routes::post_api_shop_users_create_oauth_google_login_or_signup_start() const { return *enums->_urls.POST_API_SHOP_USERS_CREATE_OAUTH_GOOGLE_LOGIN_OR_SIGNUP_START; }
QUrl Routes::post_api_shop_users_create_oauth_google_signup_complete() const { return *enums->_urls.POST_API_SHOP_USERS_CREATE_OAUTH_GOOGLE_SIGNUP_COMPLETE; }
QUrl Routes::post_api_shop_user_login() const { return *enums->_urls.POST_API_SHOP_USER_LOGIN; }
QUrl Routes::post_api_shop_user_logged_in_device() const { return *enums->_urls.POST_API_SHOP_USER_LOGGED_IN_DEVICE; }
QUrl Routes::get_api_shop_user_current_user() const { return *enums->_urls.GET_API_SHOP_USER_CURRENT_USER; }
QUrl Routes::post_api_shop_user_logout() const { return *enums->_urls.POST_API_SHOP_USER_LOGOUT; }
QUrl Routes::post_api_shop_user_recharge_coupon_id() const { return *enums->_urls.POST_API_SHOP_USER_RECHARGE_COUPON_ID; }
QUrl Routes::post_api_shop_user_recharge_coupon_code() const { return *enums->_urls.POST_API_SHOP_USER_RECHARGE_COUPON_CODE; }
QUrl Routes::post_api_shop_user_subscribe_recharge_coupon() const { return *enums->_urls.POST_API_SHOP_USER_SUBSCRIBE_RECHARGE_COUPON; }
QUrl Routes::get_api_shop_user_all_notifications() const { return *enums->_urls.GET_API_SHOP_USER_ALL_NOTIFICATIONS; }
QUrl Routes::post_api_shop_user_delete_older_notifications() const { return *enums->_urls.POST_API_SHOP_USER_DELETE_OLDER_NOTIFICATIONS; }
QUrl Routes::get_api_shop_user_logged_in_devices() const { return *enums->_urls.GET_API_SHOP_USER_LOGGED_IN_DEVICES; }
QUrl Routes::post_api_shop_join_request() const { return *enums->_urls.POST_API_SHOP_JOIN_REQUEST; }
QUrl Routes::post_api_shop_shops_populated_shop() const { return *enums->_urls.POST_API_SHOP_SHOPS_POPULATED_SHOP; }
QUrl Routes::post_api_shop_shops_create() const { return *enums->_urls.POST_API_SHOP_SHOPS_CREATE; }
QUrl Routes::post_api_shop_shop_update() const { return *enums->_urls.POST_API_SHOP_SHOP_UPDATE; }
QUrl Routes::post_api_shop_payment_prices() const { return *enums->_urls.POST_API_SHOP_PAYMENT_PRICES; }
QUrl Routes::post_api_shop_payment_generate_paytm_checksum() const { return *enums->_urls.POST_API_SHOP_PAYMENT_GENERATE_PAYTM_CHECKSUM; }
QUrl Routes::post_api_shop_payment_charge_silver_plan() const { return *enums->_urls.POST_API_SHOP_PAYMENT_CHARGE_SILVER_PLAN; }
QUrl Routes::post_api_shop_payment_charge_gold_plan() const { return *enums->_urls.POST_API_SHOP_PAYMENT_CHARGE_GOLD_PLAN; }
QUrl Routes::post_api_shop_payment_charge_onion_plan() const { return *enums->_urls.POST_API_SHOP_PAYMENT_CHARGE_ONION_PLAN; }
QUrl Routes::post_api_shop_payments_save_payment_details() const { return *enums->_urls.POST_API_SHOP_BYPASS_PAYMENTS_SAVE_PAYMENT_DETAILS; }
QUrl Routes::post_api_shop_payments_payments_history() const { return *enums->_urls.POST_API_SHOP_PAYMENTS_PAYMENTS_HISTORY; }
QUrl Routes::post_api_shop_bypass_payments_save_payment_details() const { return *enums->_urls.POST_API_SHOP_BYPASS_PAYMENTS_SAVE_PAYMENT_DETAILS; }
QUrl Routes::post_api_shop_shop_state() const { return *enums->_urls.POST_API_SHOP_SHOP_STATE; }
QUrl Routes::post_api_shop_shop_notice_board() const { return *enums->_urls.POST_API_SHOP_SHOP_NOTICE_BOARD; }
QUrl Routes::post_api_shop_shop_product_update() const { return *enums->_urls.POST_API_SHOP_SHOP_PRODUCT_UPDATE; }
QUrl Routes::post_api_shop_shop_all_touched_repo_products() const { return *enums->_urls.POST_API_SHOP_SHOP_ALL_TOUCHED_REPO_PRODUCTS; }
QUrl Routes::post_api_shop_shop_products_import() const { return *enums->_urls.POST_API_SHOP_SHOP_PRODUCTS_IMPORT; }
QUrl Routes::post_api_shop_shop_products_partial_owner_search_in_stock() const { return *enums->_urls.POST_API_SHOP_SHOP_PRODUCTS_PARTIAL_OWNER_SEARCH_IN_STOCK; }
QUrl Routes::post_api_shop_shop_products_partial_owner_with_ids() const { return *enums->_urls.POST_API_SHOP_SHOP_PRODUCTS_PARTIAL_OWNER_WITH_IDS; }
QUrl Routes::post_api_shop_shop_products_shop_product() const { return *enums->_urls.POST_API_SHOP_SHOP_PRODUCTS_SHOP_PRODUCT; }
QUrl Routes::post_api_shop_shop_all_shop_products_ids() const { return *enums->_urls.POST_API_SHOP_SHOP_ALL_SHOP_PRODUCTS_IDS; }
QUrl Routes::post_api_shop_shop_product_offer() const { return *enums->_urls.POST_API_SHOP_SHOP_PRODUCT_OFFER; }
QUrl Routes::post_api_shop_shop_product_visibility() const { return *enums->_urls.POST_API_SHOP_SHOP_PRODUCT_VISIBILITY; }
QUrl Routes::post_api_shop_shop_product_push_showcase() const { return *enums->_urls.POST_API_SHOP_SHOP_PRODUCT_PUSH_SHOWCASE; }
QUrl Routes::post_api_shop_shop_product_remove_showcase() const { return *enums->_urls.POST_API_SHOP_SHOP_PRODUCT_REMOVE_SHOWCASE; }
QUrl Routes::post_api_shop_shop_deactivate() const { return *enums->_urls.POST_API_SHOP_SHOP_DEACTIVATE; }
QUrl Routes::post_api_shop_shop_product_delete() const { return *enums->_urls.POST_API_SHOP_SHOP_PRODUCT_DELETE; }
QUrl Routes::post_api_worker_shop_state_check() const { return *enums->_urls.POST_API_WORKER_SHOP_STATE_CHECK; }
QUrl Routes::post_api_worker_shop_state_refresh_showcase() const { return *enums->_urls.POST_API_WORKER_SHOP_STATE_REFRESH_SHOWCASE; }
QUrl Routes::post_api_worker_shop_balance_ids() const { return *enums->_urls.POST_API_WORKER_SHOP_BALANCE_IDS; }
QUrl Routes::post_api_worker_shop_products_import_mass() const { return *enums->_urls.POST_API_WORKER_SHOP_PRODUCTS_IMPORT_MASS; }
QUrl Routes::post_api_worker_shop_product_delete_multiple() const { return *enums->_urls.POST_API_WORKER_SHOP_PRODUCT_DELETE_MULTIPLE; }
QUrl Routes::post_api_worker_shop_product_visibility_multiple() const { return *enums->_urls.POST_API_WORKER_SHOP_PRODUCT_VISIBILITY_MULTIPLE; }
QUrl Routes::post_api_worker_shop_all_shop_product_and_repo_product_ids() const { return *enums->_urls.POST_API_ENV_PRODUCT_REPOSITORY_ALL_REPO_PRODUCT_IDS; }
QUrl Routes::post_api_shop_shop_ib_received() const { return *enums->_urls.POST_API_SHOP_SHOP_IB_RECEIVED; }
QUrl Routes::post_api_shop_shop_update_stocks() const { return *enums->_urls.POST_API_SHOP_SHOP_UPDATE_STOCKS; }
QUrl Routes::post_api_shop_shop_left_hand() const { return *enums->_urls.POST_API_SHOP_SHOP_LEFT_HAND; }
QUrl Routes::post_api_shop_shop_products_import_via_qr() const { return *enums->_urls.POST_API_SHOP_SHOP_PRODUCTS_IMPORT_VIA_QR; }
QUrl Routes::post_api_common_user_update() const { return *enums->_urls.POST_API_COMMON_USER_UPDATE; }
QUrl Routes::post_api_common_user_reset_password_request() const { return *enums->_urls.POST_API_COMMON_USER_RESET_PASSWORD_REQUEST; }
QUrl Routes::post_api_common_user_report_bug() const { return *enums->_urls.POST_API_COMMON_USER_REPORT_BUG; }
QUrl Routes::get_api_helper_counters_all() const { return *enums->_urls.GET_API_HELPER_COUNTERS_ALL; }
QUrl Routes::get_api_helper_si_units_all() const { return *enums->_urls.GET_API_HELPER_SI_UNITS_ALL; }
QUrl Routes::get_api_helper_counteries_all() const { return *enums->_urls.GET_API_HELPER_COUNTRIES_ALL; }
QUrl Routes::get_api_helper_currencies_all() const { return *enums->_urls.GET_API_HELPER_CURRENCIES_ALL; }
QUrl Routes::get_api_helper_categories_all() const { return *enums->_urls.GET_API_HELPER_CATEGORIES_ALL; }
QUrl Routes::get_api_helper_secret_keys_all() const { return *enums->_urls.GET_API_HELPER_SECRET_KEYS_ALL; }
QUrl Routes::get_api_helper_services_all() const { return *enums->_urls.GET_API_HELPER_SERVICES_ALL; }
QUrl Routes::get_api_helper_payment_methods_all() const { return *enums->_urls.GET_API_HELPER_PAYMENT_METHODS_ALL; }
QUrl Routes::get_api_helper_onboarded_companies_all() const { return *enums->_urls.GET_API_HELPER_ONBOARDED_COMPANIES_ALL; }
QUrl Routes::post_api_env_v3_repo_products_partial_guest_search() const { return *enums->_urls.POST_API_ENV_V3_REPO_PRODUCTS_PARTIAL_GUEST_SEARCH; }
QUrl Routes::post_api_env_repo_products_repo_product() const { return *enums->_urls.POST_API_ENV_REPO_PRODUCTS_REPO_PRODUCT; }
QUrl Routes::post_api_env_repo_products_partial_search_inside() const { return *enums->_urls.POST_API_ENV_REPO_PRODUCTS_PARTIAL_SEARCH_INSIDE; }
QUrl Routes::post_api_env_repo_products_partial_with_ids() const { return *enums->_urls.POST_API_ENV_REPO_PRODUCTS_PARTIAL_WITH_IDS; }
QUrl Routes::post_api_env_product_repository_all_repo_product_ids() const { return *enums->_urls.POST_API_ENV_PRODUCT_REPOSITORY_ALL_REPO_PRODUCT_IDS; }
QUrl Routes::post_api_env_product_repositories_partial_search() const { return *enums->_urls.POST_API_ENV_PRODUCT_REPOSITORIES_PARTIAL_SEARCH; }
