#ifndef MYEXTERNALLIB_GLOBAL_H
#define MYEXTERNALLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYEXTERNALLIB_LIBRARY)
#  define MYEXTERNALLIB_EXPORT Q_DECL_EXPORT
#else
#  define MYEXTERNALLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // MYEXTERNALLIB_GLOBAL_H
